
servers=[
  {
    :hostname => "database",
    :box => "hashicorp/bionic64",
    :playbook => "./playbook/database.yml",
    :networks => [
      { :ip => "192.168.60.10" },  # backend-database
    ],
    :port => 5432,
    :forwarded_port => false
  },
  {
    :hostname => "backend",
    :box => "ubuntu/jammy64",
    :playbook => "./playbook/backend.yml",
    :networks => [
      { :ip => "192.168.60.11" },  # backend-database
      { :ip => "192.168.61.11" }   # frontend-backend
    ],
    :port => 5000,
    :forwarded_port => false
  },
  {
    :hostname => "frontend",
    :box => "ubuntu/jammy64",
    :playbook => "./playbook/frontend.yml",
    :networks => [
      { :ip => "192.168.61.10" } # frontend-backend
    ],
    :port => 8080,
    :forwarded_port => true
  }
]



Vagrant.configure("2") do |config|

    servers.each do |machine|
        config.vm.provider "virtualbox" do |vb|
          vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ] # Fix for (VERR_PATH_NOT_FOUND) error
        end
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]

            machine[:networks].each do |network|
              node.vm.network "private_network", ip: network[:ip]
            end

            if machine[:forwarded_port]
              node.vm.network :forwarded_port,
                :guest => machine[:port],
                :host => machine[:port],
                :host_ip => "127.0.0.1"
            end
            node.vm.provision :ansible, :playbook => machine[:playbook]
        end
    end
end
