apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-frontend
  namespace: frontend
  labels:
    app: cloud-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-frontend
  template:
    metadata:
      labels:
        app: cloud-frontend
    spec:
      containers:
      - name: cloud-frontend
        image: frontend:latest
        ports:
        - name: main-port
          containerPort: 80
        resources:
          requests: &requests
            cpu: "100m"
            memory: "400Mi"
          limits: *requests
        env:
          - name: BACKEND_PORT
            value: "5000"
          - name: BACKEND_HOST
            value: "backend-service.backend.svc.cluster.local"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 5
        
      
# TODO: Add service here