- hosts: all
  become: true

  tasks:
    - name: Install python and dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Install rsync
      apt:
        name: rsync
        state: present

    - name: Copy application code to VM 2
      synchronize:
        src: ../../stage_1/backend/
        dest: /backend/
        rsync_opts:
          - "--exclude=.env"
          - "--exclude=venv"

    - name: Install python requirements
      pip:
        requirements: /backend/requirements.txt
        virtualenv: /backend/venv
        virtualenv_command: python3 -m venv

    - name: Create env file
      copy:
        dest: /backend/.env
        content: |
          DATABASE_PORT=5432
          DATABASE_HOST=192.168.60.10

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/backend.service
        content: |
          [Unit]
          Description=Backend API
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/backend
          Environment="PYTHONUNBUFFERED=1"
          EnvironmentFile=/backend/.env
          ExecStart=/backend/venv/bin/python main.py
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start backend service
      systemd:
        name: backend
        state: started
        enabled: yes