apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-database
  namespace: database
  labels:
    app: cloud-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-database
  template:
    metadata:
      labels:
        app: cloud-database
    spec:
      containers:
      - name: cloud-database
        image: postgres:15.17
        ports:
        - containerPort: 5432
        resources:
          requests: &requests
            cpu: "500m"
            memory: "800Mi"
          limits: *requests
        env:
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_DB
            value: "postgres"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
            - -d
            - postgres
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 5
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/postgresql/data
          subPath: postgres 
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: database-persistent-volume-claim 
        
      
