apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-database
  labels:
    app: cloud-database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-database
  template:
    metadata:
      labels:
        app: cloud-database
    spec:
      containers:
      - name: cloud-database
        image: database:1.0.0
        ports:
        - containerPort: 5432
        resources:
          requests: &requests
            cpu: "500m"
            memory: "800Mi"
          limits: *requests
        livenessProbe:
          exec:
            command:
            - ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 5
          volumeMounts:
          - name: db-volume
            mountPath: /var/lib/postgresql/data
        
      
