apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: database-volume-class
  selector:
    matchLabels:
      release: "database"
    matchExpressions:
      - {key: environment, operator: In, values: [prod]}