
services:
  db:
    image: postgres:15.17
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    container_name: "cloud-db"
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ] # Probably should adjust parameters here
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      
  backend:
    image: cloud-systems/backend
    build:
      context: ..
      dockerfile: ./stage_3/backend/Dockerfile
    container_name: "cloud-backend"
    depends_on:
      db: 
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl", "127.0.0.1:5000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      PORT: 5432
      HOST: "db"
    ports: 
     - "0.0.0.0:5000:5000"
        
  frontend:
    image: cloud-systems/frontend
    build:
      context: ..
      dockerfile: ./stage_3/frontend/Dockerfile
      args:
        VITE_HOST: "127.0.0.1"
        VITE_PORT: 5000
    container_name: "cloud-frontend"
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - "0.0.0.0:8080:80"